# Generated by Django 2.1.1 on 2018-09-14 23:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('causale', models.CharField(max_length=100)),
                ('data', models.DateTimeField(default=datetime.date.today)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
