# Generated by Django 2.1.1 on 2018-09-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180915_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipospesa',
            name='colore',
            field=models.CharField(default='grey', max_length=30),
            preserve_default=False,
        ),
    ]
