# Generated by Django 2.1.1 on 2018-09-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tipospesa_colore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spesa',
            old_name='categoria',
            new_name='tipo_spesa',
        ),
        migrations.RenameField(
            model_name='tipospesa',
            old_name='colore',
            new_name='colore_badge',
        ),
        migrations.RemoveField(
            model_name='spesa',
            name='spesa_ordinaria',
        ),
        migrations.AddField(
            model_name='tipospesa',
            name='spesa_ordinaria',
            field=models.BooleanField(default=False),
        ),
    ]
